<?php

declare(strict_types=1);

return [
    'name' => 'Profile',
    'education' => [
        ['identifier' => 'edu0', 'name' => 'profile::options.education.high_school'],
        ['identifier' => 'edu1', 'name' => 'profile::options.education.trade_school'],
        ['identifier' => 'edu2', 'name' => 'profile::options.education.in_college'],
        ['identifier' => 'edu3', 'name' => 'profile::options.education.undergraduate'],
        ['identifier' => 'edu4', 'name' => 'profile::options.education.in_grad_school'],
        ['identifier' => 'edu5', 'name' => 'profile::options.education.graduate'],
    ],
    'body_types' => [
        ['identifier' => 'body0', 'name' => 'profile::options.body.thin'],
        ['identifier' => 'body1', 'name' => 'profile::options.body.overweight'],
        ['identifier' => 'body2', 'name' => 'profile::options.body.average'],
        ['identifier' => 'body3', 'name' => 'profile::options.body.fit'],
        ['identifier' => 'body4', 'name' => 'profile::options.body.jacked'],
        ['identifier' => 'body5', 'name' => 'profile::options.body.little_extra'],
        ['identifier' => 'body6', 'name' => 'profile::options.body.curvy'],
        ['identifier' => 'body7', 'name' => 'profile::options.body.full_figured'],
    ],
    'politics' => [
        ['identifier' => 'pol0', 'name' => 'profile::options.politics.liberal'],
        ['identifier' => 'pol1', 'name' => 'profile::options.politics.moderate'],
        ['identifier' => 'pol2', 'name' => 'profile::options.politics.conservative'],
        ['identifier' => 'pol3', 'name' => 'profile::options.politics.other'],
    ],
    'ethnicities' => [
        ['identifier' => 'eth0', 'name' => 'profile::options.ethnicity.asian'],
        ['identifier' => 'eth1', 'name' => 'profile::options.ethnicity.black'],
        ['identifier' => 'eth2', 'name' => 'profile::options.ethnicity.hispanic'],
        ['identifier' => 'eth3', 'name' => 'profile::options.ethnicity.indian'],
        ['identifier' => 'eth4', 'name' => 'profile::options.ethnicity.middle_eastern'],
        ['identifier' => 'eth5', 'name' => 'profile::options.ethnicity.native_american'],
        ['identifier' => 'eth6', 'name' => 'profile::options.ethnicity.pacific_islander'],
        ['identifier' => 'eth7', 'name' => 'profile::options.ethnicity.white'],
        ['identifier' => 'eth8', 'name' => 'profile::options.ethnicity.other'],
    ],
    'languages' => [
        ['identifier' => 'lang0', 'name' => 'profile::options.language.english'],
        ['identifier' => 'lang1', 'name' => 'profile::options.language.afrikaans'],
        ['identifier' => 'lang2', 'name' => 'profile::options.language.albanian'],
        ['identifier' => 'lang3', 'name' => 'profile::options.language.arabic'],
        ['identifier' => 'lang4', 'name' => 'profile::options.language.armenian'],
        ['identifier' => 'lang5', 'name' => 'profile::options.language.basque'],
        ['identifier' => 'lang6', 'name' => 'profile::options.language.belarusian'],
        ['identifier' => 'lang7', 'name' => 'profile::options.language.bengali'],
        ['identifier' => 'lang8', 'name' => 'profile::options.language.breton'],
        ['identifier' => 'lang9', 'name' => 'profile::options.language.bulgarian'],
        ['identifier' => 'lang10', 'name' => 'profile::options.language.catalan'],
        ['identifier' => 'lang11', 'name' => 'profile::options.language.cebuano'],
        ['identifier' => 'lang12', 'name' => 'profile::options.language.chechen'],
        ['identifier' => 'lang13', 'name' => 'profile::options.language.chinese'],
        ['identifier' => 'lang14', 'name' => 'profile::options.language.chinese_cantonese'],
        ['identifier' => 'lang15', 'name' => 'profile::options.language.chinese_mandarin'],
        ['identifier' => 'lang16', 'name' => 'profile::options.language.cplusplus'],
        ['identifier' => 'lang17', 'name' => 'profile::options.language.croatian'],
        ['identifier' => 'lang18', 'name' => 'profile::options.language.czech'],
        ['identifier' => 'lang19', 'name' => 'profile::options.language.danish'],
        ['identifier' => 'lang20', 'name' => 'profile::options.language.dutch'],
        ['identifier' => 'lang21', 'name' => 'profile::options.language.esperanto'],
        ['identifier' => 'lang22', 'name' => 'profile::options.language.estonian'],
        ['identifier' => 'lang23', 'name' => 'profile::options.language.finnish'],
        ['identifier' => 'lang24', 'name' => 'profile::options.language.french'],
        ['identifier' => 'lang25', 'name' => 'profile::options.language.frisian'],
        ['identifier' => 'lang26', 'name' => 'profile::options.language.georgian'],
        ['identifier' => 'lang27', 'name' => 'profile::options.language.german'],
        ['identifier' => 'lang28', 'name' => 'profile::options.language.greek'],
        ['identifier' => 'lang29', 'name' => 'profile::options.language.gujarati'],
        ['identifier' => 'lang30', 'name' => 'profile::options.language.ancient_greek'],
        ['identifier' => 'lang31', 'name' => 'profile::options.language.hawaiian'],
        ['identifier' => 'lang32', 'name' => 'profile::options.language.hebrew'],
        ['identifier' => 'lang33', 'name' => 'profile::options.language.hindi'],
        ['identifier' => 'lang34', 'name' => 'profile::options.language.hungarian'],
        ['identifier' => 'lang35', 'name' => 'profile::options.language.icelandic'],
        ['identifier' => 'lang36', 'name' => 'profile::options.language.ilongo'],
        ['identifier' => 'lang37', 'name' => 'profile::options.language.indonesian'],
        ['identifier' => 'lang38', 'name' => 'profile::options.language.irish'],
        ['identifier' => 'lang39', 'name' => 'profile::options.language.italian'],
        ['identifier' => 'lang40', 'name' => 'profile::options.language.japanese'],
        ['identifier' => 'lang41', 'name' => 'profile::options.language.khmer'],
        ['identifier' => 'lang42', 'name' => 'profile::options.language.korean'],
        ['identifier' => 'lang43', 'name' => 'profile::options.language.latin'],
        ['identifier' => 'lang44', 'name' => 'profile::options.language.latvian'],
        ['identifier' => 'lang45', 'name' => 'profile::options.language.lisp'],
        ['identifier' => 'lang46', 'name' => 'profile::options.language.lithuanian'],
        ['identifier' => 'lang47', 'name' => 'profile::options.language.malay'],
        ['identifier' => 'lang48', 'name' => 'profile::options.language.maori'],
        ['identifier' => 'lang49', 'name' => 'profile::options.language.mongolian'],
        ['identifier' => 'lang50', 'name' => 'profile::options.language.norwegian'],
        ['identifier' => 'lang51', 'name' => 'profile::options.language.occitan'],
        ['identifier' => 'lang52', 'name' => 'profile::options.language.other_language'],
        ['identifier' => 'lang53', 'name' => 'profile::options.language.persian'],
        ['identifier' => 'lang54', 'name' => 'profile::options.language.polish'],
        ['identifier' => 'lang55', 'name' => 'profile::options.language.portuguese'],
        ['identifier' => 'lang56', 'name' => 'profile::options.language.punjabi'],
        ['identifier' => 'lang57', 'name' => 'profile::options.language.romanian'],
        ['identifier' => 'lang58', 'name' => 'profile::options.language.rotuman'],
        ['identifier' => 'lang59', 'name' => 'profile::options.language.russian'],
        ['identifier' => 'lang60', 'name' => 'profile::options.language.sanskrit'],
        ['identifier' => 'lang61', 'name' => 'profile::options.language.sardinian'],
        ['identifier' => 'lang62', 'name' => 'profile::options.language.serbian'],
        ['identifier' => 'lang63', 'name' => 'profile::options.language.sign_language'],
        ['identifier' => 'lang64', 'name' => 'profile::options.language.slovak'],
        ['identifier' => 'lang65', 'name' => 'profile::options.language.slovenian'],
        ['identifier' => 'lang66', 'name' => 'profile::options.language.spanish'],
        ['identifier' => 'lang67', 'name' => 'profile::options.language.swahili'],
        ['identifier' => 'lang68', 'name' => 'profile::options.language.swedish'],
        ['identifier' => 'lang69', 'name' => 'profile::options.language.tagalog'],
        ['identifier' => 'lang70', 'name' => 'profile::options.language.tamil'],
        ['identifier' => 'lang71', 'name' => 'profile::options.language.thai'],
        ['identifier' => 'lang72', 'name' => 'profile::options.language.tibetan'],
        ['identifier' => 'lang73', 'name' => 'profile::options.language.turkish'],
        ['identifier' => 'lang74', 'name' => 'profile::options.language.ukrainian'],
        ['identifier' => 'lang75', 'name' => 'profile::options.language.urdu'],
        ['identifier' => 'lang76', 'name' => 'profile::options.language.vietnamese'],
        ['identifier' => 'lang77', 'name' => 'profile::options.language.welsh'],
        ['identifier' => 'lang78', 'name' => 'profile::options.language.yiddish'],
    ],
    'pronouns' => [
        ['identifier' => 'prn1', 'name' => 'profile::options.pronouns.he_him'],
        ['identifier' => 'prn2', 'name' => 'profile::options.pronouns.she_her'],
        ['identifier' => 'prn3', 'name' => 'profile::options.pronouns.they_them'],
        ['identifier' => 'custom', 'name' => 'profile::options.pronouns.custom'],
    ],
    'diet' => [
        ['identifier' => 'diet0', 'name' => 'profile::options.diet.omnivore'],
        ['identifier' => 'diet1', 'name' => 'profile::options.diet.vegetarian'],
        ['identifier' => 'diet2', 'name' => 'profile::options.diet.vegan'],
        ['identifier' => 'diet3', 'name' => 'profile::options.diet.kosher'],
        ['identifier' => 'diet4', 'name' => 'profile::options.diet.halal'],
        ['identifier' => 'diet5', 'name' => 'profile::options.diet.gluten_free'],
        ['identifier' => 'diet6', 'name' => 'profile::options.diet.pescatarian'],
        ['identifier' => 'diet7', 'name' => 'profile::options.diet.jain'],
        ['identifier' => 'diet8', 'name' => 'profile::options.diet.lactovegetarian'],
        ['identifier' => 'diet9', 'name' => 'profile::options.diet.if'],
        ['identifier' => 'diet10', 'name' => 'profile::options.diet.keto'],
    ],
    'employment' => [
        ['identifier' => 'job0', 'name' => 'profile::options.employment.full_time'],
        ['identifier' => 'job1', 'name' => 'profile::options.employment.part_time'],
        ['identifier' => 'job2', 'name' => 'profile::options.employment.freelance'],
        ['identifier' => 'job3', 'name' => 'profile::options.employment.self_employed'],
        ['identifier' => 'job4', 'name' => 'profile::options.employment.unemployed'],
        ['identifier' => 'job5', 'name' => 'profile::options.employment.retired'],
    ],
    'religion' => [
        ['identifier' => 'rel0', 'name' => 'profile::options.religion.agnosticism'],
        ['identifier' => 'rel1', 'name' => 'profile::options.religion.atheism'],
        ['identifier' => 'rel2', 'name' => 'profile::options.religion.christianity'],
        ['identifier' => 'rel3', 'name' => 'profile::options.religion.judaism'],
        ['identifier' => 'rel4', 'name' => 'profile::options.religion.catholicism'],
        ['identifier' => 'rel5', 'name' => 'profile::options.religion.islam'],
        ['identifier' => 'rel6', 'name' => 'profile::options.religion.hinduism'],
        ['identifier' => 'rel7', 'name' => 'profile::options.religion.buddhism'],
        ['identifier' => 'rel8', 'name' => 'profile::options.religion.sikh'],
        ['identifier' => 'rel9', 'name' => 'profile::options.religion.other'],
    ],
    'smoke' => [
        ['identifier' => 'cig0', 'name' => 'profile::options.smoke.regularly'],
        ['identifier' => 'cig1', 'name' => 'profile::options.smoke.sometimes'],
        ['identifier' => 'cig2', 'name' => 'profile::options.smoke.never'],
    ],
    'drink' => [
        ['identifier' => 'alcohol0', 'name' => 'profile::options.drink.often'],
        ['identifier' => 'alcohol1', 'name' => 'profile::options.drink.sometimes'],
        ['identifier' => 'alcohol2', 'name' => 'profile::options.drink.never'],
    ],
    'drugs' => [
        ['identifier' => 'weed0', 'name' => 'profile::options.drugs.often'],
        ['identifier' => 'weed1', 'name' => 'profile::options.drugs.sometimes'],
        ['identifier' => 'weed2', 'name' => 'profile::options.drugs.never'],
    ],
    'relationship_type' => [
        ['identifier' => 'rel1', 'name' => 'profile::options.relationship.monogamous', 'description' => 'profile::options.relationship.monogamous_desc'],
        ['identifier' => 'rel2', 'name' => 'profile::options.relationship.non_monogamous', 'description' => 'profile::options.relationship.non_monogamous_desc'],
        ['identifier' => 'rel3', 'name' => 'profile::options.relationship.open_to_either', 'description' => 'profile::options.relationship.open_to_either_desc'],
    ],
    'children' => [
        ['identifier' => 'child0', 'name' => 'profile::options.children.none_maybe'],
        ['identifier' => 'child1', 'name' => 'profile::options.children.none_yes'],
        ['identifier' => 'child2', 'name' => 'profile::options.children.none_never'],
        ['identifier' => 'child3', 'name' => 'profile::options.children.has_none'],
        ['identifier' => 'child4', 'name' => 'profile::options.children.has_maybe'],
        ['identifier' => 'child5', 'name' => 'profile::options.children.has_yes'],
    ],
    'pets' => [
        ['identifier' => 'none', 'name' => 'profile::options.pets.none'],
        ['identifier' => 'other', 'name' => 'profile::options.pets.other'],
        ['identifier' => 'cat', 'name' => 'profile::options.pets.cat'],
        ['identifier' => 'dog', 'name' => 'profile::options.pets.dog'],
    ],
    'genders' => [
        ['identifier' => 'gen1', 'name' => 'profile::options.gender.woman'],
        ['identifier' => 'gen2', 'name' => 'profile::options.gender.man'],
        ['identifier' => 'gen3', 'name' => 'profile::options.gender.agender', 'description' => 'profile::options.gender.agender_desc'],
        ['identifier' => 'gen4', 'name' => 'profile::options.gender.androgynous', 'description' => 'profile::options.gender.androgynous_desc'],
        ['identifier' => 'gen5', 'name' => 'profile::options.gender.bigender', 'description' => 'profile::options.gender.bigender_desc'],
        ['identifier' => 'gen6', 'name' => 'profile::options.gender.cis_man', 'description' => 'profile::options.gender.cis_man_desc'],
        ['identifier' => 'gen7', 'name' => 'profile::options.gender.cis_woman', 'description' => 'profile::options.gender.cis_woman_desc'],
        ['identifier' => 'gen8', 'name' => 'profile::options.gender.genderfluid', 'description' => 'profile::options.gender.genderfluid_desc'],
        ['identifier' => 'gen9', 'name' => 'profile::options.gender.genderqueer', 'description' => 'profile::options.gender.genderqueer_desc'],
        ['identifier' => 'gen10', 'name' => 'profile::options.gender.gender_nonconforming', 'description' => 'profile::options.gender.gender_nonconforming_desc'],
        ['identifier' => 'gen11', 'name' => 'profile::options.gender.hijra', 'description' => 'profile::options.gender.hijra_desc'],
        ['identifier' => 'gen12', 'name' => 'profile::options.gender.intersex', 'description' => 'profile::options.gender.intersex_desc'],
        ['identifier' => 'gen13', 'name' => 'profile::options.gender.non_binary', 'description' => 'profile::options.gender.non_binary_desc'],
        ['identifier' => 'gen14', 'name' => 'profile::options.gender.other_gender', 'description' => 'profile::options.gender.other_gender_desc'],
        ['identifier' => 'gen15', 'name' => 'profile::options.gender.pangender', 'description' => 'profile::options.gender.pangender_desc'],
        ['identifier' => 'gen16', 'name' => 'profile::options.gender.transfeminine', 'description' => 'profile::options.gender.transfeminine_desc'],
        ['identifier' => 'gen17', 'name' => 'profile::options.gender.transgender', 'description' => 'profile::options.gender.transgender_desc'],
        ['identifier' => 'gen18', 'name' => 'profile::options.gender.trans_man', 'description' => 'profile::options.gender.trans_man_desc'],
        ['identifier' => 'gen19', 'name' => 'profile::options.gender.transmasculine', 'description' => 'profile::options.gender.transmasculine_desc'],
        ['identifier' => 'gen20', 'name' => 'profile::options.gender.transsexual', 'description' => 'profile::options.gender.transsexual_desc'],
        ['identifier' => 'gen21', 'name' => 'profile::options.gender.trans_woman', 'description' => 'profile::options.gender.trans_woman_desc'],
        ['identifier' => 'gen22', 'name' => 'profile::options.gender.two_spirit', 'description' => 'profile::options.gender.two_spirit_desc'],
    ],

    'orientations' => [
        ['identifier' => 'ori0', 'name' => 'profile::options.orientation.straight', 'description' => 'profile::options.orientation.straight_desc'],
        ['identifier' => 'ori1', 'name' => 'profile::options.orientation.gay', 'description' => 'profile::options.orientation.gay_desc'],
        ['identifier' => 'ori2', 'name' => 'profile::options.orientation.bisexual', 'description' => 'profile::options.orientation.bisexual_desc'],
        ['identifier' => 'ori3', 'name' => 'profile::options.orientation.asexual', 'description' => 'profile::options.orientation.asexual_desc'],
        ['identifier' => 'ori4', 'name' => 'profile::options.orientation.demisexual', 'description' => 'profile::options.orientation.demisexual_desc'],
        ['identifier' => 'ori5', 'name' => 'profile::options.orientation.homoflexible', 'description' => 'profile::options.orientation.homoflexible_desc'],
        ['identifier' => 'ori6', 'name' => 'profile::options.orientation.heteroflexible', 'description' => 'profile::options.orientation.heteroflexible_desc'],
        ['identifier' => 'ori7', 'name' => 'profile::options.orientation.lesbian', 'description' => 'profile::options.orientation.lesbian_desc'],
        ['identifier' => 'ori8', 'name' => 'profile::options.orientation.pansexual', 'description' => 'profile::options.orientation.pansexual_desc'],
        ['identifier' => 'ori9', 'name' => 'profile::options.orientation.queer', 'description' => 'profile::options.orientation.queer_desc'],
        ['identifier' => 'ori10', 'name' => 'profile::options.orientation.questioning', 'description' => 'profile::options.orientation.questioning_desc'],
        ['identifier' => 'ori12', 'name' => 'profile::options.orientation.gray_asexual', 'description' => 'profile::options.orientation.gray_asexual_desc'],
        ['identifier' => 'ori13', 'name' => 'profile::options.orientation.reciprosexual', 'description' => 'profile::options.orientation.reciprosexual_desc'],
        ['identifier' => 'ori14', 'name' => 'profile::options.orientation.akiosexual', 'description' => 'profile::options.orientation.akiosexual_desc'],
        ['identifier' => 'ori15', 'name' => 'profile::options.orientation.aceflux', 'description' => 'profile::options.orientation.aceflux_desc'],
        ['identifier' => 'ori16', 'name' => 'profile::options.orientation.grayromantic', 'description' => 'profile::options.orientation.grayromantic_desc'],
        ['identifier' => 'ori17', 'name' => 'profile::options.orientation.demiromantic', 'description' => 'profile::options.orientation.demiromantic_desc'],
        ['identifier' => 'ori18', 'name' => 'profile::options.orientation.recipromantic', 'description' => 'profile::options.orientation.recipromantic_desc'],
        ['identifier' => 'ori19', 'name' => 'profile::options.orientation.akioromantic', 'description' => 'profile::options.orientation.akioromantic_desc'],
        ['identifier' => 'ori20', 'name' => 'profile::options.orientation.aroflux', 'description' => 'profile::options.orientation.aroflux_desc'],
        ['identifier' => 'ori21', 'name' => 'profile::options.orientation.skoliosexual', 'description' => 'profile::options.orientation.skoliosexual_desc'],
    ],
];
